# Generated by Django 5.2.7 on 2025-10-18 21:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denomination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(default='#3498db', help_text='Hex color code for calendar display', max_length=7, verbose_name='color code')),
                ('icon', models.CharField(blank=True, help_text='Icon name for display', max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('church_branch', models.ForeignKey(blank=True, help_text='Leave blank for denomination-wide categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='denomination.churchbranch', verbose_name='church branch')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
                'db_table': 'event_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='event title')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('event_type', models.CharField(choices=[('regular', 'Regular Event'), ('recurring', 'Recurring Event'), ('special', 'Special Event')], default='regular', max_length=20, verbose_name='event type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='status')),
                ('start_datetime', models.DateTimeField(verbose_name='start date & time')),
                ('end_datetime', models.DateTimeField(verbose_name='end date & time')),
                ('all_day', models.BooleanField(default=False, verbose_name='all day event')),
                ('recurrence_pattern', models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20, verbose_name='recurrence pattern')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='recurrence end date')),
                ('location', models.CharField(max_length=300, verbose_name='location')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='venue name')),
                ('address', models.TextField(blank=True, verbose_name='full address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_online', models.BooleanField(default=False, verbose_name='online event')),
                ('meeting_link', models.URLField(blank=True, verbose_name='meeting link')),
                ('meeting_id', models.CharField(blank=True, max_length=100, verbose_name='meeting ID')),
                ('meeting_password', models.CharField(blank=True, max_length=100, verbose_name='meeting password')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum attendees')),
                ('require_rsvp', models.BooleanField(default=True, verbose_name='require RSVP')),
                ('rsvp_deadline', models.DateTimeField(blank=True, null=True, verbose_name='RSVP deadline')),
                ('allow_guests', models.BooleanField(default=False, verbose_name='allow guests')),
                ('max_guests_per_person', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max guests per person')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to non-members', verbose_name='public event')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/', verbose_name='banner image')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('dress_code', models.CharField(blank=True, max_length=100, verbose_name='dress code')),
                ('special_instructions', models.TextField(blank=True, verbose_name='special instructions')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300, verbose_name='tags')),
                ('send_reminder', models.BooleanField(default=True, verbose_name='send reminder')),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Send reminder X hours before event', verbose_name='reminder hours before')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('church_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='denomination.churchbranch', verbose_name='church branch')),
                ('department', models.ForeignKey(blank=True, help_text='Department organizing this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='denomination.branchdepartment', verbose_name='department')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='organizer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], default='email', max_length=20, verbose_name='reminder type')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='delivery status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'event reminder',
                'verbose_name_plural': 'event reminders',
                'db_table': 'event_reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False, verbose_name='checked in')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='check-in time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='check-out time')),
                ('check_in_method', models.CharField(choices=[('manual', 'Manual'), ('qr_code', 'QR Code'), ('nfc', 'NFC'), ('facial', 'Facial Recognition')], default='manual', max_length=20, verbose_name='check-in method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='events.event', verbose_name='event')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'event attendance',
                'verbose_name_plural': 'event attendances',
                'db_table': 'event_attendances',
                'ordering': ['-check_in_time'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not Going'), ('maybe', 'Maybe'), ('waitlist', 'Waitlist')], default='going', max_length=20, verbose_name='RSVP status')),
                ('number_of_guests', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of guests')),
                ('guest_names', models.TextField(blank=True, help_text='Names of guests (one per line)', verbose_name='guest names')),
                ('dietary_requirements', models.TextField(blank=True, verbose_name='dietary requirements')),
                ('special_needs', models.TextField(blank=True, verbose_name='special needs')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('confirmation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='confirmation code')),
                ('confirmed', models.BooleanField(default=True, verbose_name='confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'db_table': 'event_rsvps',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
