# Generated by Django 4.2.7 on 2025-10-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("donation", "Donation"),
                            ("announcement", "Announcement"),
                            ("message", "Message"),
                            ("attendance", "Attendance"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect when clicked",
                        null=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        default="in_app",
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="sent")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
