# Generated by Django 5.2.7 on 2025-10-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('denomination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='church_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='denomination.churchbranch', verbose_name='church branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='denomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='denomination.denomination', verbose_name='denomination'),
        ),
    ]
