# Generated by Django 5.2.7 on 2025-10-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='denomination name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='denominations/logos/%Y/%m/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='denominations/covers/%Y/%m/', verbose_name='cover image')),
                ('headquarters', models.CharField(blank=True, max_length=300, verbose_name='headquarters')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='active', max_length=20, verbose_name='status')),
                ('allow_public_registration', models.BooleanField(default=True, help_text='Allow people to register and join this denomination', verbose_name='allow public registration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_denominations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'denomination',
                'verbose_name_plural': 'denominations',
                'db_table': 'denominations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChurchBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='branch name')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/images/%Y/%m/', verbose_name='branch image')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('country', models.CharField(default='Nigeria', max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='alternative phone')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_construction', 'Under Construction')], default='active', max_length=20, verbose_name='status')),
                ('service_times', models.TextField(blank=True, help_text='Example: Sunday: 8AM, 10AM | Wednesday: 6PM', verbose_name='service times')),
                ('seating_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of people the church can accommodate', null=True, verbose_name='seating capacity')),
                ('is_headquarters', models.BooleanField(default=False, verbose_name='is headquarters')),
                ('allow_online_giving', models.BooleanField(default=True, verbose_name='allow online giving')),
                ('allow_event_registration', models.BooleanField(default=True, verbose_name='allow event registration')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='established date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_branches', to=settings.AUTH_USER_MODEL, verbose_name='branch admin')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='denomination.denomination', verbose_name='denomination')),
            ],
            options={
                'verbose_name': 'church branch',
                'verbose_name_plural': 'church branches',
                'db_table': 'church_branches',
                'ordering': ['denomination', 'name'],
                'unique_together': {('denomination', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BranchDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='department name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='department head')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='denomination.churchbranch', verbose_name='church branch')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'branch_departments',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
