# Generated by Django 5.2.7 on 2025-10-19 18:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denomination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tag name')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'media tag',
                'verbose_name_plural': 'media tags',
                'db_table': 'media_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='media.mediacategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'media category',
                'verbose_name_plural': 'media categories',
                'db_table': 'media_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('media_type', models.CharField(choices=[('sermon', 'Sermon'), ('music', 'Music/Song'), ('book', 'Book/E-book'), ('video', 'Video'), ('podcast', 'Podcast'), ('devotional', 'Devotional'), ('testimony', 'Testimony'), ('other', 'Other')], max_length=20, verbose_name='media type')),
                ('author', models.CharField(max_length=200, verbose_name='author/speaker')),
                ('recorded_date', models.DateField(blank=True, null=True, verbose_name='recorded date')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='published date')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/%Y/%m/', verbose_name='thumbnail')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'aac'])], verbose_name='audio file')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/video/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='video file')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='media/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'mobi', 'doc', 'docx'])], verbose_name='document file')),
                ('external_video_url', models.URLField(blank=True, verbose_name='external video URL')),
                ('external_audio_url', models.URLField(blank=True, verbose_name='external audio URL')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration for audio/video', null=True, verbose_name='duration (seconds)')),
                ('series', models.CharField(blank=True, max_length=200, verbose_name='series name')),
                ('series_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='series number')),
                ('scripture_references', models.TextField(blank=True, help_text='Bible verses referenced', verbose_name='scripture references')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='language')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('branch_only', 'Branch Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('allow_download', models.BooleanField(default=True, verbose_name='allow download')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='play count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='media.mediacategory', verbose_name='category')),
                ('church_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='denomination.churchbranch', verbose_name='church branch')),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='denomination.denomination', verbose_name='denomination')),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministered_media', to=settings.AUTH_USER_MODEL, verbose_name='minister (if user)')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('tags', models.ManyToManyField(blank=True, related_name='media_items', to='media.mediatag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'media item',
                'verbose_name_plural': 'media items',
                'db_table': 'media_items',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('is_approved', models.BooleanField(default=True, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='media.mediacomment', verbose_name='parent comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.mediaitem', verbose_name='media item')),
            ],
            options={
                'verbose_name': 'media comment',
                'verbose_name_plural': 'media comments',
                'db_table': 'media_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='playlist name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/playlists/%Y/%m/', verbose_name='playlist thumbnail')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('church_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_playlists', to='denomination.churchbranch', verbose_name='church branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_playlists', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'media playlist',
                'verbose_name_plural': 'media playlists',
                'db_table': 'media_playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_memberships', to='media.mediaitem', verbose_name='media item')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='media.mediaplaylist', verbose_name='playlist')),
            ],
            options={
                'verbose_name': 'playlist item',
                'verbose_name_plural': 'playlist items',
                'db_table': 'playlist_items',
                'ordering': ['order', 'added_at'],
                'unique_together': {('playlist', 'media_item')},
            },
        ),
        migrations.AddField(
            model_name='mediaplaylist',
            name='media_items',
            field=models.ManyToManyField(related_name='playlists', through='media.PlaylistItem', to='media.mediaitem', verbose_name='media items'),
        ),
        migrations.CreateModel(
            name='MediaFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_favorites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='media.mediaitem', verbose_name='media item')),
            ],
            options={
                'verbose_name': 'media favorite',
                'verbose_name_plural': 'media favorites',
                'db_table': 'media_favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_item')},
            },
        ),
        migrations.CreateModel(
            name='MediaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('review', models.TextField(blank=True, verbose_name='review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='media.mediaitem', verbose_name='media item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'media rating',
                'verbose_name_plural': 'media ratings',
                'db_table': 'media_ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_item')},
            },
        ),
    ]
