# Generated by Django 5.2.7 on 2025-10-18 21:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denomination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='membership number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='active', max_length=20, verbose_name='member status')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, verbose_name='marital status')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='occupation')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='employer')),
                ('spouse_name', models.CharField(blank=True, max_length=200, verbose_name='spouse name')),
                ('anniversary_date', models.DateField(blank=True, null=True, verbose_name='wedding anniversary')),
                ('number_of_children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='number of children')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='baptism date')),
                ('baptism_location', models.CharField(blank=True, max_length=200, verbose_name='baptism location')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='confirmation date')),
                ('previous_church', models.CharField(blank=True, max_length=200, verbose_name='previous church')),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to='members/transfers/%Y/%m/', verbose_name='transfer letter')),
                ('skills', models.TextField(blank=True, help_text='e.g., Singing, Teaching, Technical skills', verbose_name='skills/talents')),
                ('interests', models.TextField(blank=True, help_text='Areas of interest in church activities', verbose_name='interests')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='date joined church')),
                ('membership_approved_date', models.DateField(blank=True, null=True, verbose_name='membership approved date')),
                ('notes', models.TextField(blank=True, help_text='Private notes (only visible to admins)', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('membership_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_confidential', models.BooleanField(default=True, help_text='Only visible to church leadership', verbose_name='confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_notes', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'member note',
                'verbose_name_plural': 'member notes',
                'db_table': 'member_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='membership type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('can_vote', models.BooleanField(default=True, verbose_name='can vote')),
                ('can_hold_office', models.BooleanField(default=True, verbose_name='can hold office')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('church_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='denomination.churchbranch', verbose_name='church branch')),
            ],
            options={
                'verbose_name': 'membership type',
                'verbose_name_plural': 'membership types',
                'db_table': 'membership_types',
                'ordering': ['church_branch', 'name'],
                'unique_together': {('church_branch', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.membershiptype', verbose_name='membership type'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='e.g., Sunday Service, Bible Study', max_length=200, verbose_name='event/service name')),
                ('date', models.DateField(verbose_name='attendance date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20, verbose_name='status')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='check-in time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='check-out time')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('church_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='denomination.churchbranch', verbose_name='church branch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'db_table': 'attendances',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('member', 'date', 'event_name')},
            },
        ),
        migrations.CreateModel(
            name='MemberDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Coordinator, Assistant, Member', max_length=100, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='joined date')),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='left date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_members', to='denomination.branchdepartment', verbose_name='department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_departments', to='members.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'member department',
                'verbose_name_plural': 'member departments',
                'db_table': 'member_departments',
                'ordering': ['member', 'department'],
                'unique_together': {('member', 'department')},
            },
        ),
    ]
